"""empty message

Revision ID: 2258e53ad53e
Revises: 0bb271735546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2258e53ad53e'
down_revision = '0bb271735546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
