"""Adding stripe_session to User attributes

Revision ID: 2418db059cd2
Revises: 811d6503629a
Create Date: 2020-02-14 02:27:18.469131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2418db059cd2'
down_revision = '811d6503629a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_session_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_session_id')
    # ### end Alembic commands ###
