"""Test

Revision ID: 3e37f4921bb8
Revises: 9f7ad35516ca
Create Date: 2020-03-20 12:18:01.723989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e37f4921bb8'
down_revision = '9f7ad35516ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('content', sa.String(length=240), nullable=True))
    op.add_column('tasks', sa.Column('opportunity_step_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('title', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'tasks', 'opportunity_steps', ['opportunity_step_id'], ['id'])
    op.drop_column('tasks', 'task_content')
    op.drop_column('tasks', 'task_title')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.add_column('tasks', sa.Column('task_title', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('tasks', sa.Column('task_content', mysql.VARCHAR(length=240), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'title')
    op.drop_column('tasks', 'opportunity_step_id')
    op.drop_column('tasks', 'content')
    # ### end Alembic commands ###
