"""empty message

Revision ID: 516f07da7b6e
Revises: cd43443329f5
Create Date: 2020-04-07 21:02:23.793775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '516f07da7b6e'
down_revision = 'cd43443329f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('leads')

    # op.add_column('companies', sa.Column('country', sa.String(length=60), nullable=True))
    op.add_column('lead_requests', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('lead_requests', sa.Column('company_lead_id', sa.Integer(), nullable=True))
    op.add_column('lead_requests', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.add_column('lead_requests', sa.Column('contact_lead_id', sa.Integer(), nullable=True))
    op.add_column('lead_requests', sa.Column('id', sa.Integer(), nullable=False))
    
    
    op.drop_constraint('lead_requests_ibfk_1', 'lead_requests', type_='foreignkey')
    op.drop_constraint('lead_requests_ibfk_2', 'lead_requests', type_='foreignkey')


    op.drop_column('lead_requests', 'user_id')
    op.create_foreign_key(None, 'lead_requests', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'lead_requests', 'contact_leads', ['contact_lead_id'], ['id'])
    op.create_foreign_key(None, 'lead_requests', 'company_leads', ['company_lead_id'], ['id'])
    op.create_foreign_key(None, 'lead_requests', 'companies', ['company_id'], ['id'])
    op.drop_column('lead_requests', 'lead_id')
    op.drop_column('notes', 'comapny_id')
    op.add_column('plans', sa.Column('category', sa.String(length=30), nullable=True))
    op.add_column('plans', sa.Column('free_trial', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('name', sa.String(length=30), nullable=True))
    op.add_column('plans', sa.Column('stripe_id', sa.String(length=120), nullable=True))
    op.add_column('plans', sa.Column('yearly', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.drop_index('ix_plans_plan_name', table_name='plans')
    op.drop_column('plans', 'yearly_price')
    op.drop_column('plans', 'plan_name')
    op.add_column('users', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.add_column('plans', sa.Column('plan_name', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('plans', sa.Column('yearly_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_plans_plan_name', 'plans', ['plan_name'], unique=False)
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_column('plans', 'yearly')
    op.drop_column('plans', 'stripe_id')
    op.drop_column('plans', 'name')
    op.drop_column('plans', 'free_trial')
    op.drop_column('plans', 'category')
    op.add_column('notes', sa.Column('comapny_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('lead_requests', sa.Column('lead_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lead_requests', type_='foreignkey')
    op.drop_constraint(None, 'lead_requests', type_='foreignkey')
    op.drop_constraint(None, 'lead_requests', type_='foreignkey')
    op.drop_constraint(None, 'lead_requests', type_='foreignkey')
    op.create_foreign_key('lead_requests_ibfk_1', 'lead_requests', 'leads', ['lead_id'], ['id'])
    op.alter_column('lead_requests', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('lead_requests', 'id')
    op.drop_column('lead_requests', 'contact_lead_id')
    op.drop_column('lead_requests', 'contact_id')
    op.drop_column('lead_requests', 'company_lead_id')
    op.drop_column('lead_requests', 'company_id')
    op.drop_column('companies', 'country')
    # op.create_table('leads',
    # sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    # sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    # sa.Column('company_name', mysql.VARCHAR(length=120), nullable=True),
    # sa.Column('company_address', mysql.VARCHAR(length=120), nullable=True),
    # sa.Column('company_postal_code', mysql.VARCHAR(length=30), nullable=True),
    # sa.Column('company_city', mysql.VARCHAR(length=60), nullable=True),
    # sa.Column('company_email', mysql.VARCHAR(length=120), nullable=True),
    # sa.Column('company_email_bcc', mysql.VARCHAR(length=120), nullable=True),
    # sa.Column('company_phone', mysql.VARCHAR(length=60), nullable=True),
    # sa.Column('company_activity_field', mysql.VARCHAR(length=60), nullable=False),
    # sa.Column('owner_firstname', mysql.VARCHAR(length=60), nullable=True),
    # sa.Column('owner_lastname', mysql.VARCHAR(length=60), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_default_charset='utf8',
    # mysql_engine='InnoDB'
    # )
    # op.create_table('subscriptions',
    # sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    # sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    # sa.Column('yearly', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    # sa.Column('subscription_date', mysql.DATETIME(), nullable=True),
    # sa.Column('next_payment', mysql.DATETIME(), nullable=True),
    # sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='subscriptions_ibfk_1'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_ibfk_2'),
    # sa.PrimaryKeyConstraint('plan_id', 'user_id'),
    # mysql_default_charset='utf8',
    # mysql_engine='InnoDB'
    # )
    # ### end Alembic commands ###
