"""New user attribute: stripe_customer_id

Revision ID: 9f7ad35516ca
Revises: 2418db059cd2
Create Date: 2020-02-19 01:54:30.733648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f7ad35516ca'
down_revision = '2418db059cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=256), nullable=True))
    op.drop_column('users', 'stripe_session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_session_id', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
