"""New plan attribute

Revision ID: ba5ad2438ac4
Revises: 9f7ad35516ca
Create Date: 2020-02-21 15:34:09.953283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba5ad2438ac4'
down_revision = '9f7ad35516ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('lead_generator', sa.Boolean(), nullable=True))
    op.drop_column('plans', 'crm_access')
    op.add_column('subscriptions', sa.Column('next_payment', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'next_payment')
    op.add_column('plans', sa.Column('crm_access', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('plans', 'lead_generator')
    # ### end Alembic commands ###
