"""empty message

Revision ID: eb0cc42bca99
Revises: 6add373fe14f
Create Date: 2020-04-08 20:44:52.175787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb0cc42bca99'
down_revision = '6add373fe14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commercial_stage_steps_ibfk_1', 'commercial_stage_steps', type_='foreignkey')
    op.drop_column('commercial_stage_steps', 'commercial_stage_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commercial_stage_steps', sa.Column('commercial_stage_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('commercial_stage_steps_ibfk_1', 'commercial_stage_steps', 'commercial_stages', ['commercial_stage_id'], ['id'])
    # ### end Alembic commands ###
