"""Changing names in tables

Revision ID: b55786f8acb6
Revises: 965bd97ac24e
Create Date: 2020-02-27 23:37:24.158842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55786f8acb6'
down_revision = '965bd97ac24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('closing_perc', sa.Numeric(precision=2, scale=2), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oppportunity_stages',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('commercial_step_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commercial_step_id'], ['commercial_steps.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('opportunity_id', 'commercial_step_id', 'status_id')
    )
    op.drop_table('commercial_stage_steps')
    op.drop_table('commercial_stages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_stages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=60), nullable=True),
    sa.Column('closing_perc', sa.NUMERIC(precision=2, scale=2), nullable=True),
    sa.Column('private', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('private IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commercial_stage_steps',
    sa.Column('opportunity_id', sa.INTEGER(), nullable=False),
    sa.Column('commercial_stage_id', sa.INTEGER(), nullable=False),
    sa.Column('status_id', sa.INTEGER(), nullable=False),
    sa.Column('note_id', sa.INTEGER(), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('creation_date', sa.DATETIME(), nullable=True),
    sa.Column('last_update', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['commercial_stage_id'], ['commercial_stages.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('opportunity_id', 'commercial_stage_id', 'status_id')
    )
    op.drop_table('oppportunity_stages')
    op.drop_table('commercial_steps')
    # ### end Alembic commands ###
