"""empty message

Revision ID: 002287808f51
Revises: 16a512bb0139
Create Date: 2020-04-07 20:44:57.192643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002287808f51'
down_revision = '16a512bb0139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    # ### end Alembic commands ###
