"""empty message

Revision ID: 009d1f1b3177
Revises: 133931006387
Create Date: 2020-04-03 00:24:26.709674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009d1f1b3177'
down_revision = '133931006387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_leads', sa.Column('facebook', sa.String(length=120), nullable=True))
    op.add_column('company_leads', sa.Column('instagram', sa.String(length=120), nullable=True))
    op.add_column('company_leads', sa.Column('linkedin', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_leads', 'linkedin')
    op.drop_column('company_leads', 'instagram')
    op.drop_column('company_leads', 'facebook')
    # ### end Alembic commands ###
