"""empty message

Revision ID: 067024032e81
Revises: a9ba70177083
Create Date: 2020-04-04 23:30:06.483128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067024032e81'
down_revision = 'a9ba70177083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
