"""empty message

Revision ID: 0b57dfa1ce56
Revises: 75be08b4099c
Create Date: 2020-03-28 02:30:25.979899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b57dfa1ce56'
down_revision = '75be08b4099c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_requests', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('lead_requests_contact_lead_id', table_name='lead_requests')
    op.create_foreign_key(None, 'lead_requests', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'lead_requests', 'contact_leads', ['contact_lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_requests', type_='foreignkey')
    op.drop_constraint(None, 'lead_requests', type_='foreignkey')
    op.create_index('lead_requests_contact_lead_id', 'lead_requests', ['contact_lead_id'], unique=False)
    op.drop_column('lead_requests', 'user_id')
    # ### end Alembic commands ###
