"""empty message

Revision ID: 0c5b5a2ee052
Revises: 445dee1525df
Create Date: 2020-04-08 20:51:24.255718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c5b5a2ee052'
down_revision = '445dee1525df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commercial_stage_steps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_stage_steps',
    sa.Column('status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('note_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_update', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name='commercial_stage_steps_ibfk_2'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name='commercial_stage_steps_ibfk_4'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='commercial_stage_steps_ibfk_5'),
    sa.PrimaryKeyConstraint('status_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
