"""[ADD] New attribute User table

Revision ID: 0f6dd6b5699c
Revises: 22f75dbbe195
Create Date: 2020-02-29 23:47:47.456149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6dd6b5699c'
down_revision = '22f75dbbe195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
