"""empty message

Revision ID: 133931006387
Revises: c2a72a3e8e58
Create Date: 2020-03-30 00:07:02.036398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133931006387'
down_revision = 'c2a72a3e8e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('contact_leads_ibfk_10', 'contact_leads', type_='foreignkey')
    # op.drop_constraint('contacts_ibfk_3', 'contact_leads', type_='foreignkey')
    # op.drop_constraint(None, 'contact_leads', type_='foreignkey')
    op.drop_column('contact_leads', 'company_id')
    op.add_column('contact_leads', sa.Column('company_id', sa.Integer()))
    op.create_foreign_key('fk30_03_1', 'contact_leads', 'company_leads', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
	pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('fk30_03_1', 'contact_leads', type_='foreignkey')
    # op.drop_column('contact_leads', 'company_id')
    # ### end Alembic commands ###
