"""empty message

Revision ID: 1444c9491962
Revises: 237d570ac384
Create Date: 2020-03-28 02:02:14.587231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1444c9491962'
down_revision = '237d570ac384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_leads_activity_field1', table_name='contacts_leads')
    op.drop_index('ix_contacts_leads_activity_field2', table_name='contacts_leads')
    op.drop_index('ix_contacts_leads_activity_field3', table_name='contacts_leads')
    op.drop_table('contacts_leads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts_leads',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('activity_field1', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('activity_field2', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('activity_field3', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('company_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('firstname', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('linkedin', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('position', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_contacts_leads_activity_field3', 'contacts_leads', ['activity_field3'], unique=False)
    op.create_index('ix_contacts_leads_activity_field2', 'contacts_leads', ['activity_field2'], unique=False)
    op.create_index('ix_contacts_leads_activity_field1', 'contacts_leads', ['activity_field1'], unique=False)
    # ### end Alembic commands ###
