"""empty message

Revision ID: 16a512bb0139
Revises: 2b59db0776cd
Create Date: 2020-04-07 20:42:12.671954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a512bb0139'
down_revision = '2b59db0776cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    # ### end Alembic commands ###
