"""empty message

Revision ID: 1ca54f8d333e
Revises: e5711ffc81e3
Create Date: 2020-03-16 01:30:55.751079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ca54f8d333e'
down_revision = 'e5711ffc81e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content', sa.String(length=240), nullable=True))
    op.drop_column('notes', 'note_content')
    op.add_column('tasks', sa.Column('content', sa.String(length=240), nullable=True))
    op.add_column('tasks', sa.Column('title', sa.String(length=60), nullable=True))
    op.drop_column('tasks', 'task_content')
    op.drop_column('tasks', 'task_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_title', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('tasks', sa.Column('task_content', mysql.VARCHAR(length=240), nullable=True))
    op.drop_column('tasks', 'title')
    op.drop_column('tasks', 'content')
    op.add_column('notes', sa.Column('note_content', mysql.VARCHAR(length=240), nullable=True))
    op.drop_column('notes', 'content')
    # ### end Alembic commands ###
