"""Adding position in contact table

Revision ID: 21250d9c34d9
Revises: 420232a13447
Create Date: 2020-03-14 00:24:37.610791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21250d9c34d9'
down_revision = '420232a13447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('position', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_contacts_position'), 'contacts', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_position'), table_name='contacts')
    op.drop_column('contacts', 'position')
    # ### end Alembic commands ###
