"""[ADD] new attribute "last_token" to user database

Revision ID: 22f75dbbe195
Revises: ee7ec109ff28
Create Date: 2020-02-29 00:41:55.316200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f75dbbe195'
down_revision = 'ee7ec109ff28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_token', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_token')
    # ### end Alembic commands ###
