"""empty message

Revision ID: 2370135b2fe4
Revises: 1ca54f8d333e
Create Date: 2020-03-23 04:03:36.243323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2370135b2fe4'
down_revision = '1ca54f8d333e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('notes_ibfk_1', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'companies', ['company_id'], ['id'])
    op.drop_column('notes', 'comapny_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('comapny_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_ibfk_1', 'notes', 'companies', ['comapny_id'], ['id'])
    op.drop_column('notes', 'company_id')
    # ### end Alembic commands ###
