"""New fields for Contact

Revision ID: 27ba5d85a15d
Revises: bbada0113f65
Create Date: 2020-01-30 05:39:46.440738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ba5d85a15d'
down_revision = 'bbada0113f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('facebook', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('instagram', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('linkedin', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'website')
    op.drop_column('contacts', 'linkedin')
    op.drop_column('contacts', 'instagram')
    op.drop_column('contacts', 'facebook')
    # ### end Alembic commands ###
