"""empty message

Revision ID: 2b59db0776cd
Revises: 995b8a4bdd7b
Create Date: 2020-04-06 13:23:52.402856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b59db0776cd'
down_revision = '995b8a4bdd7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('category', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'category')
    # ### end Alembic commands ###
