"""[ADD] one-to-many relationship btw CommercialStepChange and Status

Revision ID: 2d8b402af198
Revises: 01ae0348b697
Create Date: 2020-01-26 23:08:55.147752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d8b402af198'
down_revision = '01ae0348b697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'note_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('note_title', mysql.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
