"""Add email field within ContactsEmail

Revision ID: 420232a13447
Revises: a7aeca672715
Create Date: 2020-03-13 14:47:07.601690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '420232a13447'
down_revision = 'a7aeca672715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_emails', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('contacts_emails', sa.Column('main_email', sa.Boolean(), nullable=True))
    op.drop_column('contacts_emails', 'professional')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_emails', sa.Column('professional', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('contacts_emails', 'main_email')
    op.drop_column('contacts_emails', 'email')
    # ### end Alembic commands ###
