"""empty message

Revision ID: 445dee1525df
Revises: d5a6175665f6
Create Date: 2020-04-08 20:47:29.231390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '445dee1525df'
down_revision = 'd5a6175665f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commercial_stage_steps_ibfk_1', 'commercial_stage_steps', type_='foreignkey')
    op.drop_column('commercial_stage_steps', 'commercial_stage_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commercial_stage_steps', sa.Column('commercial_stage_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('commercial_stage_steps_ibfk_1', 'commercial_stage_steps', 'commercial_stages', ['commercial_stage_id'], ['id'])
    # ### end Alembic commands ###
