"""[ADD] New attribute User table

Revision ID: 4626aff7da4d
Revises: 0f6dd6b5699c
Create Date: 2020-02-29 23:49:20.689110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4626aff7da4d'
down_revision = '0f6dd6b5699c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_token')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('users', sa.Column('last_token', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
