"""Test

Revision ID: 4a713c31624c
Revises: b8fe376c1b7d
Create Date: 2020-03-12 23:28:52.382725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a713c31624c'
down_revision = 'b8fe376c1b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('professional', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['commercial_stages.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contacts', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('phone', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_contacts_first_name'), 'contacts', ['first_name'], unique=False)
    op.create_index(op.f('ix_contacts_last_name'), 'contacts', ['last_name'], unique=False)
    op.drop_index('ix_contacts_company_activity_field', table_name='contacts')
    op.drop_index('ix_contacts_owner_firstname', table_name='contacts')
    op.drop_index('ix_contacts_owner_lastname', table_name='contacts')
    op.drop_column('contacts', 'company_activity_field')
    op.drop_column('contacts', 'company_address')
    op.drop_column('contacts', 'company_city')
    op.drop_column('contacts', 'owner_lastname')
    op.drop_column('contacts', 'company_postal_code')
    op.drop_column('contacts', 'owner_firstname')
    op.drop_column('contacts', 'company_phone')
    op.drop_column('contacts', 'company_email')
    op.drop_column('contacts', 'website')
    op.drop_column('contacts', 'company_email_bcc')
    op.drop_column('contacts', 'company_name')
    op.add_column('notes', sa.Column('comapny_id', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('opportunity_step_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'companies', ['comapny_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'opportunity_steps', ['opportunity_step_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'contacts', ['contact_id'], ['id'])
    op.add_column('tasks', sa.Column('opportunity_step_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'opportunity_steps', ['opportunity_step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'opportunity_step_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'opportunity_step_id')
    op.drop_column('notes', 'contact_id')
    op.drop_column('notes', 'comapny_id')
    op.add_column('contacts', sa.Column('company_name', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contacts', sa.Column('company_email_bcc', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contacts', sa.Column('website', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contacts', sa.Column('company_email', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contacts', sa.Column('company_phone', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('contacts', sa.Column('owner_firstname', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('contacts', sa.Column('company_postal_code', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('contacts', sa.Column('owner_lastname', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('contacts', sa.Column('company_city', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('contacts', sa.Column('company_address', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contacts', sa.Column('company_activity_field', mysql.VARCHAR(length=60), nullable=False))
    op.create_index('ix_contacts_owner_lastname', 'contacts', ['owner_lastname'], unique=False)
    op.create_index('ix_contacts_owner_firstname', 'contacts', ['owner_firstname'], unique=False)
    op.create_index('ix_contacts_company_activity_field', 'contacts', ['company_activity_field'], unique=False)
    op.drop_index(op.f('ix_contacts_last_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_first_name'), table_name='contacts')
    op.drop_column('contacts', 'phone')
    op.drop_column('contacts', 'last_name')
    op.drop_column('contacts', 'first_name')
    op.drop_table('opportunity_steps')
    op.drop_table('contacts_emails')
    # ### end Alembic commands ###
