"""fixing bugs in names inside Contact

Revision ID: 58c06d0bef24
Revises: eca4ac91750d
Create Date: 2020-03-14 12:00:15.460656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58c06d0bef24'
down_revision = 'eca4ac91750d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('contacts_ibfk_1', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'companies', ['company_id'], ['id'])
    op.drop_column('contacts', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('company', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_ibfk_1', 'contacts', 'companies', ['company'], ['id'])
    op.drop_column('contacts', 'company_id')
    # ### end Alembic commands ###
