"""empty message

Revision ID: 62d434e32a03
Revises: 198e01c77ac4
Create Date: 2020-04-03 00:45:37.838644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62d434e32a03'
down_revision = '198e01c77ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('country', sa.String(length=60), nullable=True))
    op.drop_column('companies', 'countr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('countr', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('companies', 'country')
    # ### end Alembic commands ###
