"""empty message

Revision ID: 689367f24bbc
Revises: 9920b130b247
Create Date: 2020-04-26 06:38:57.821052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689367f24bbc'
down_revision = '9920b130b247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('cancelation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'cancelation_date')
    # ### end Alembic commands ###
