"""empty message

Revision ID: 75be08b4099c
Revises: 9dc0e8a7af2f
Create Date: 2020-03-28 02:20:29.393626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75be08b4099c'
down_revision = '9dc0e8a7af2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###
