"""empty message

Revision ID: 78e7554e5ee4
Revises: 19e5b6b954f0
Create Date: 2020-04-07 20:57:46.390337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78e7554e5ee4'
down_revision = '19e5b6b954f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('subscription_date', mysql.DATETIME(), nullable=True),
    sa.Column('next_payment', mysql.DATETIME(), nullable=True),
    sa.Column('stripe_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_ibfk_2'),
    sa.PrimaryKeyConstraint('plan_id', 'user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
