"""empty message

Revision ID: 8451e08c6ea1
Revises: a7fbd30b9207
Create Date: 2020-04-03 16:09:35.120716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8451e08c6ea1'
down_revision = 'a7fbd30b9207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_requests', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('lead_requests', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead_requests', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'lead_requests', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_requests', type_='foreignkey')
    op.drop_constraint(None, 'lead_requests', type_='foreignkey')
    op.drop_column('lead_requests', 'contact_id')
    op.drop_column('lead_requests', 'company_id')
    # ### end Alembic commands ###
