"""empty message

Revision ID: 8d90107af5e3
Revises: 8ddf5eba224d
Create Date: 2020-03-29 19:07:41.619359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d90107af5e3'
down_revision = '8ddf5eba224d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_leads_ibfk_1', 'contact_leads', type_='foreignkey')
    op.drop_column('contact_leads', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_leads', sa.Column('company', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('contact_leads_ibfk_1', 'contact_leads', 'company_leads', ['company'], ['id'])
    # ### end Alembic commands ###
