"""empty message

Revision ID: 8ddf5eba224d
Revises: add4021ee877
Create Date: 2020-03-29 19:01:46.592056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ddf5eba224d'
down_revision = 'add4021ee877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_leads', 'contact_position')
    op.drop_column('company_leads', 'contact_firstname')
    op.drop_column('company_leads', 'contact_lastname')
    op.add_column('contact_leads', sa.Column('company', sa.Integer(), nullable=True))
    op.drop_index('ix_contact_leads_activity_field1', table_name='contact_leads')
    op.drop_index('ix_contact_leads_activity_field2', table_name='contact_leads')
    op.drop_index('ix_contact_leads_activity_field3', table_name='contact_leads')
    op.create_foreign_key(None, 'contact_leads', 'company_leads', ['company'], ['id'])
    op.drop_column('contact_leads', 'company_name')
    op.drop_column('contact_leads', 'activity_field3')
    op.drop_column('contact_leads', 'activity_field1')
    op.drop_column('contact_leads', 'activity_field2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_leads', sa.Column('activity_field2', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contact_leads', sa.Column('activity_field1', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('contact_leads', sa.Column('activity_field3', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contact_leads', sa.Column('company_name', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'contact_leads', type_='foreignkey')
    op.create_index('ix_contact_leads_activity_field3', 'contact_leads', ['activity_field3'], unique=False)
    op.create_index('ix_contact_leads_activity_field2', 'contact_leads', ['activity_field2'], unique=False)
    op.create_index('ix_contact_leads_activity_field1', 'contact_leads', ['activity_field1'], unique=False)
    op.drop_column('contact_leads', 'company')
    op.add_column('company_leads', sa.Column('contact_lastname', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('company_leads', sa.Column('contact_firstname', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('company_leads', sa.Column('contact_position', mysql.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
