"""empty message

Revision ID: 9920b130b247
Revises: aa4f9d80c3fb
Create Date: 2020-04-18 02:27:36.363007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9920b130b247'
down_revision = 'aa4f9d80c3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_email')
    # ### end Alembic commands ###
