"""empty message

Revision ID: 9dc0e8a7af2f
Revises: 1444c9491962
Create Date: 2020-03-28 02:02:50.619515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc0e8a7af2f'
down_revision = '1444c9491962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('linkedin', sa.String(length=120), nullable=True),
    sa.Column('activity_field1', sa.String(length=120), nullable=False),
    sa.Column('activity_field2', sa.String(length=120), nullable=True),
    sa.Column('activity_field3', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_leads_activity_field1'), 'contact_leads', ['activity_field1'], unique=False)
    op.create_index(op.f('ix_contact_leads_activity_field2'), 'contact_leads', ['activity_field2'], unique=False)
    op.create_index(op.f('ix_contact_leads_activity_field3'), 'contact_leads', ['activity_field3'], unique=False)
    op.add_column('lead_requests', sa.Column('contact_lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key('lead_requests_contact_lead_id', 'lead_requests', 'contact_leads', ['contact_lead_id'], ['id']) #create_foreign_key(constraint_name, source_table, referent_table, local_cols, remote_cols, onupdate=None, ondelete=None,....)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lead_requests_contact_lead_id', 'lead_requests', type_='foreignkey')
    op.drop_column('lead_requests', 'contact_lead_id')
    op.drop_index(op.f('ix_contact_leads_activity_field3'), table_name='contact_leads')
    op.drop_index(op.f('ix_contact_leads_activity_field2'), table_name='contact_leads')
    op.drop_index(op.f('ix_contact_leads_activity_field1'), table_name='contact_leads')
    op.drop_table('contact_leads')
    # ### end Alembic commands ###
