"""empty message

Revision ID: 9f82c4bf68fe
Revises: 2370135b2fe4
Create Date: 2020-03-23 23:28:50.977865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f82c4bf68fe'
down_revision = '2370135b2fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('free_trial', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('name', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.drop_index('ix_plans_plan_name', table_name='plans')
    op.drop_column('plans', 'plan_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('plan_name', mysql.VARCHAR(length=30), nullable=True))
    op.create_index('ix_plans_plan_name', 'plans', ['plan_name'], unique=False)
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_column('plans', 'name')
    op.drop_column('plans', 'free_trial')
    # ### end Alembic commands ###
