"""empty message

Revision ID: a0391b81c9b7
Revises: be3964036946
Create Date: 2020-03-28 02:00:11.027123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0391b81c9b7'
down_revision = 'be3964036946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_leads', sa.Column('activity_field1', sa.String(length=120), nullable=False))
    op.add_column('contacts_leads', sa.Column('activity_field2', sa.String(length=120), nullable=True))
    op.add_column('contacts_leads', sa.Column('activity_field3', sa.String(length=120), nullable=True))
    op.add_column('contacts_leads', sa.Column('company_name', sa.String(length=120), nullable=False))
    op.add_column('contacts_leads', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('contacts_leads', sa.Column('firstname', sa.String(length=120), nullable=False))
    op.add_column('contacts_leads', sa.Column('lastname', sa.String(length=120), nullable=False))
    op.add_column('contacts_leads', sa.Column('linkedin', sa.String(length=120), nullable=True))
    op.add_column('contacts_leads', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('contacts_leads', sa.Column('position', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_contacts_leads_activity_field1'), 'contacts_leads', ['activity_field1'], unique=False)
    op.create_index(op.f('ix_contacts_leads_activity_field2'), 'contacts_leads', ['activity_field2'], unique=False)
    op.create_index(op.f('ix_contacts_leads_activity_field3'), 'contacts_leads', ['activity_field3'], unique=False)
    op.drop_column('contacts_leads', 'contact_linkedin')
    op.drop_column('contacts_leads', 'contact_activity_field1')
    op.drop_column('contacts_leads', 'contact_activity_field2')
    op.drop_column('contacts_leads', 'contact_lastname')
    op.drop_column('contacts_leads', 'contact_position')
    op.drop_column('contacts_leads', 'contact_firstname')
    op.drop_column('contacts_leads', 'contact_email')
    op.drop_column('contacts_leads', 'contact_phone')
    op.drop_column('contacts_leads', 'contact_company')
    op.drop_column('contacts_leads', 'contact_activity_field3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_leads', sa.Column('contact_activity_field3', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contacts_leads', sa.Column('contact_company', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('contacts_leads', sa.Column('contact_phone', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contacts_leads', sa.Column('contact_email', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contacts_leads', sa.Column('contact_firstname', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('contacts_leads', sa.Column('contact_position', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contacts_leads', sa.Column('contact_lastname', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('contacts_leads', sa.Column('contact_activity_field2', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('contacts_leads', sa.Column('contact_activity_field1', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('contacts_leads', sa.Column('contact_linkedin', mysql.VARCHAR(length=120), nullable=True))
    op.drop_index(op.f('ix_contacts_leads_activity_field3'), table_name='contacts_leads')
    op.drop_index(op.f('ix_contacts_leads_activity_field2'), table_name='contacts_leads')
    op.drop_index(op.f('ix_contacts_leads_activity_field1'), table_name='contacts_leads')
    op.drop_column('contacts_leads', 'position')
    op.drop_column('contacts_leads', 'phone')
    op.drop_column('contacts_leads', 'linkedin')
    op.drop_column('contacts_leads', 'lastname')
    op.drop_column('contacts_leads', 'firstname')
    op.drop_column('contacts_leads', 'email')
    op.drop_column('contacts_leads', 'company_name')
    op.drop_column('contacts_leads', 'activity_field3')
    op.drop_column('contacts_leads', 'activity_field2')
    op.drop_column('contacts_leads', 'activity_field1')
    # ### end Alembic commands ###
