"""Change crm_access to leads_generator inside plan table

Revision ID: a39cc9e878b4
Revises: 2b403a31b26f
Create Date: 2020-02-21 14:13:38.847319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a39cc9e878b4'
down_revision = '2b403a31b26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('lead_generator', sa.Boolean(), nullable=True))
    op.drop_column('plans', 'crm_access')
    op.drop_column('users', 'stripe_session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_session_id', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('plans', sa.Column('crm_access', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('plans', 'lead_generator')
    # ### end Alembic commands ###
