"""change email and phone name

Revision ID: a7aeca672715
Revises: b460c1b51177
Create Date: 2020-03-13 04:45:20.514837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7aeca672715'
down_revision = 'b460c1b51177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(length=60), nullable=True))
    op.drop_column('companies', 'contact_email')
    op.drop_column('companies', 'contact_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('contact_phone', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('companies', sa.Column('contact_email', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'email')
    # ### end Alembic commands ###
