"""empty message

Revision ID: a7fbd30b9207
Revises: 62d434e32a03
Create Date: 2020-04-03 15:48:00.032298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fbd30b9207'
down_revision = '62d434e32a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_leads', sa.Column('creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_leads', 'creation_date')
    # ### end Alembic commands ###
