"""empty message

Revision ID: aa4f9d80c3fb
Revises: 0c5b5a2ee052
Create Date: 2020-04-09 03:37:05.502656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa4f9d80c3fb'
down_revision = '0c5b5a2ee052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('opportunity_id', sa.Integer(), nullable=True))
    op.drop_constraint('notes_ibfk_2', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'opportunities', ['opportunity_id'], ['id'])
    op.drop_column('notes', 'opportunity_step_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('opportunity_step_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_ibfk_2', 'notes', 'opportunity_steps', ['opportunity_step_id'], ['id'])
    op.drop_column('notes', 'opportunity_id')
    # ### end Alembic commands ###
