"""empty message

Revision ID: add4021ee877
Revises: 5e50962d27ed
Create Date: 2020-03-29 00:23:34.123937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add4021ee877'
down_revision = '5e50962d27ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_leads', sa.Column('country', sa.String(length=60), nullable=False))
    op.create_index(op.f('ix_company_leads_country'), 'company_leads', ['country'], unique=False)
    op.add_column('contact_leads', sa.Column('country', sa.String(length=60), nullable=False))
    op.create_index(op.f('ix_contact_leads_country'), 'contact_leads', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_leads_country'), table_name='contact_leads')
    op.drop_column('contact_leads', 'country')
    op.drop_index(op.f('ix_company_leads_country'), table_name='company_leads')
    op.drop_column('company_leads', 'country')
    # ### end Alembic commands ###
