"""empty message

Revision ID: af0ebc101d01
Revises: c3f13760333c
Create Date: 2020-03-26 12:58:10.575077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af0ebc101d01'
down_revision = 'c3f13760333c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commercial_stages', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('company_leads', sa.Column('company_name', sa.String(length=120), nullable=False))
    op.drop_column('leads', 'owner_lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('owner_lastname', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('company_leads', 'company_name')
    op.alter_column('commercial_stages', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
