"""Test2

Revision ID: b298ac173e5a
Revises: 4a713c31624c
Create Date: 2020-03-13 00:15:14.963397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b298ac173e5a'
down_revision = '4a713c31624c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'companies', ['company'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'company')
    # ### end Alembic commands ###
