"""Replace Contact Table by Company Table

Revision ID: b8fe376c1b7d
Revises: ca343ce9f736
Create Date: 2020-03-11 18:04:51.579933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8fe376c1b7d'
down_revision = 'ca343ce9f736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=60), nullable=True),
    sa.Column('activity_field', sa.String(length=60), nullable=False),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('facebook', sa.String(length=120), nullable=True),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('linkedin', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_activity_field'), 'companies', ['activity_field'], unique=False)
    op.drop_constraint('contacts_ibfk_1', 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'user_id')
    op.add_column('opportunities', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('opportunities_ibfk_1', 'opportunities', type_='foreignkey')
    op.create_foreign_key(None, 'opportunities', 'companies', ['company_id'], ['id'])
    op.drop_column('opportunities', 'contact_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('contact_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.create_foreign_key('opportunities_ibfk_1', 'opportunities', 'contacts', ['contact_id'], ['id'])
    op.drop_column('opportunities', 'company_id')
    op.add_column('contacts', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('contacts_ibfk_1', 'contacts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_companies_activity_field'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
