"""empty message

Revision ID: b95bf9009b6d
Revises: 0b57dfa1ce56
Create Date: 2020-03-28 02:32:00.173055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b95bf9009b6d'
down_revision = '0b57dfa1ce56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lead_requests_ibfk_10', 'lead_requests', type_='foreignkey')
    op.drop_constraint('lead_requests_ibfk_9', 'lead_requests', type_='foreignkey')
    op.drop_constraint('lead_requests_ibfk_4', 'lead_requests', type_='foreignkey')
    op.drop_column('lead_requests', 'user_id')
    op.drop_column('lead_requests', 'contact_lead_id')
    op.drop_column('lead_requests', 'company_lead_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_requests', sa.Column('company_lead_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('lead_requests', sa.Column('contact_lead_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('lead_requests', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('lead_requests_ibfk_9', 'lead_requests', 'users', ['user_id'], ['id'])
    op.create_foreign_key('lead_requests_ibfk_8', 'lead_requests', 'company_leads', ['company_lead_id'], ['id'])
    op.create_foreign_key('lead_requests_ibfk_10', 'lead_requests', 'contact_leads', ['contact_lead_id'], ['id'])
    # ### end Alembic commands ###
