"""Change closing date to last update for Opportunity table

Revision ID: bc88dead23ba
Revises: bf0b3a836ecd
Create Date: 2020-01-28 17:00:10.920646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc88dead23ba'
down_revision = 'bf0b3a836ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.drop_column('opportunities', 'closing_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('closing_date', mysql.DATETIME(), nullable=True))
    op.drop_column('opportunities', 'last_update')
    # ### end Alembic commands ###
