"""empty message

Revision ID: be3964036946
Revises: dd8023accf0b
Create Date: 2020-03-26 14:26:59.502880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be3964036946'
down_revision = 'dd8023accf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_company_activity_field', table_name='leads')
    op.drop_index('ix_leads_contact_firstname', table_name='leads')
    op.drop_index('ix_leads_contact_lastname', table_name='leads')
    op.drop_index('ix_leads_contact_position', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('company_name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('company_address', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('company_postal_code', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('company_city', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('company_email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('company_phone', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('company_activity_field', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('contact_firstname', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('contact_lastname', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('contact_position', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('owner_lastname', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_leads_contact_position', 'leads', ['contact_position'], unique=False)
    op.create_index('ix_leads_contact_lastname', 'leads', ['contact_lastname'], unique=False)
    op.create_index('ix_leads_contact_firstname', 'leads', ['contact_firstname'], unique=False)
    op.create_index('ix_leads_company_activity_field', 'leads', ['company_activity_field'], unique=False)
    # ### end Alembic commands ###
