"""empty message

Revision ID: bfdd87919101
Revises: 689367f24bbc
Create Date: 2020-04-26 10:29:49.699039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfdd87919101'
down_revision = '689367f24bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('cancellation_date', sa.DateTime(), nullable=True))
    op.drop_column('subscriptions', 'cancelation_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('cancelation_date', mysql.DATETIME(), nullable=True))
    op.drop_column('subscriptions', 'cancellation_date')
    # ### end Alembic commands ###
