"""empty message

Revision ID: c2a72a3e8e58
Revises: 8d90107af5e3
Create Date: 2020-03-30 00:06:32.812857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2a72a3e8e58'
down_revision = '8d90107af5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_leads_ibfk_1', 'contact_leads', type_='foreignkey')
    op.drop_column('contact_leads', 'company_id')
    op.drop_column('contact_leads', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_leads', sa.Column('company', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('contact_leads', sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('contact_leads_ibfk_1', 'contact_leads', 'company_leads', ['company'], ['id'])
    # ### end Alembic commands ###
