"""empty message

Revision ID: c6d9712b7a46
Revises: 7964f9064716
Create Date: 2020-04-08 20:18:02.735383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6d9712b7a46'
down_revision = '7964f9064716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('opportunity_steps_ibfk_2', 'opportunity_steps', type_='foreignkey')
    op.drop_column('opportunity_steps', 'stage_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_steps', sa.Column('stage_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('opportunity_steps_ibfk_2', 'opportunity_steps', 'commercial_stages', ['stage_id'], ['id'])
    # ### end Alembic commands ###
