"""[ADD] New attribute User table

Revision ID: ca343ce9f736
Revises: 4626aff7da4d
Create Date: 2020-02-29 23:49:45.521114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca343ce9f736'
down_revision = '4626aff7da4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_token')
    # ### end Alembic commands ###
