"""empty message

Revision ID: d5a6175665f6
Revises: 6866454011b7
Create Date: 2020-04-08 20:32:26.021463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5a6175665f6'
down_revision = '6866454011b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commercial_stage_steps_ibfk_3', 'commercial_stage_steps', type_='foreignkey')
    op.drop_column('commercial_stage_steps', 'opportunity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commercial_stage_steps', sa.Column('opportunity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('commercial_stage_steps_ibfk_3', 'commercial_stage_steps', 'opportunities', ['opportunity_id'], ['id'])
    # ### end Alembic commands ###
