"""is_main in ContactsEmail

Revision ID: eca4ac91750d
Revises: 21250d9c34d9
Create Date: 2020-03-14 03:46:58.124700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eca4ac91750d'
down_revision = '21250d9c34d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_emails', sa.Column('is_main', sa.Boolean(), nullable=True))
    op.drop_column('contacts_emails', 'main_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_emails', sa.Column('main_email', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('contacts_emails', 'is_main')
    # ### end Alembic commands ###
