"""empty message

Revision ID: ee7ec109ff28
Revises: ccf564dafcd2
Create Date: 2020-02-28 00:52:11.259187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee7ec109ff28'
down_revision = 'ccf564dafcd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oppportunity_stages')
    op.drop_table('commercial_steps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oppportunity_stages',
    sa.Column('opportunity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('commercial_step_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('note_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_update', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['commercial_step_id'], ['commercial_steps.id'], name='oppportunity_stages_ibfk_1'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name='oppportunity_stages_ibfk_2'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name='oppportunity_stages_ibfk_3'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name='oppportunity_stages_ibfk_4'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='oppportunity_stages_ibfk_5'),
    sa.PrimaryKeyConstraint('opportunity_id', 'commercial_step_id', 'status_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('commercial_steps',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('closing_perc', mysql.DECIMAL(precision=2, scale=2), nullable=True),
    sa.Column('private', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='commercial_steps_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
