"""empty message

Revision ID: 61e65f006542
Revises: 861ddea65186
Create Date: 2020-03-16 01:51:32.470400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61e65f006542'
down_revision = '861ddea65186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('transaction_date', mysql.DATETIME(), nullable=True),
    sa.Column('affiliation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('invoice_id', mysql.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], name='transactions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
