"""empty message

Revision ID: 75125ba8bb9c
Revises: 9af402893f49
Create Date: 2020-03-16 01:26:47.951292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75125ba8bb9c'
down_revision = '9af402893f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliations', sa.Column('payment_type', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('affiliation_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('invoice_id', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'transactions', 'affiliations', ['affiliation_id'], ['id'])
    op.drop_column('transactions', 'subscription_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('subscription_id', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'invoice_id')
    op.drop_column('transactions', 'affiliation_id')
    op.drop_column('affiliations', 'payment_type')
    # ### end Alembic commands ###
