"""empty message

Revision ID: 861ddea65186
Revises: 75125ba8bb9c
Create Date: 2020-03-16 01:50:05.427420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '861ddea65186'
down_revision = '75125ba8bb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliations', 'payment_type')
    op.add_column('users', sa.Column('payment_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_type')
    op.add_column('affiliations', sa.Column('payment_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
