"""[ADD] Attempt to create new tables in order to develop features for the crm

Revision ID: 67667f0a6520
Revises: 3009dcc5afd1
Create Date: 2020-01-20 22:22:37.235599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67667f0a6520'
down_revision = '3009dcc5afd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_title', sa.String(length=60), nullable=True),
    sa.Column('note_content', sa.String(length=240), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('commercial_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('closing_perc', sa.Numeric(precision=0, scale=2), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('company_address', sa.String(length=120), nullable=True),
    sa.Column('company_postal_code', sa.String(length=30), nullable=True),
    sa.Column('company_city', sa.String(length=60), nullable=True),
    sa.Column('company_email', sa.String(length=120), nullable=True),
    sa.Column('company_email_bcc', sa.String(length=120), nullable=True),
    sa.Column('company_phone', sa.String(length=60), nullable=True),
    sa.Column('company_activity_field', sa.String(length=60), nullable=False),
    sa.Column('owner_firstname', sa.String(length=60), nullable=True),
    sa.Column('owner_lastname', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_activity_field'), 'contacts', ['company_activity_field'], unique=False)
    op.create_index(op.f('ix_contacts_owner_firstname'), 'contacts', ['owner_firstname'], unique=False)
    op.create_index(op.f('ix_contacts_owner_lastname'), 'contacts', ['owner_lastname'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_title', sa.String(length=60), nullable=True),
    sa.Column('task_content', sa.String(length=240), nullable=True),
    sa.Column('priority', sa.String(length=30), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('euro_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('deal_closed', sa.Boolean(), nullable=True),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commercial_stage_steps',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('commercial_stage_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commercial_stage_id'], ['commercial_stages.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('opportunity_id', 'commercial_stage_id', 'status_id')
    )
    op.drop_index('ix_customers_company_activity_field', table_name='customers')
    op.drop_index('ix_customers_owner_firstname', table_name='customers')
    op.drop_index('ix_customers_owner_lastname', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('company_name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('company_address', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('company_postal_code', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('company_city', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('company_email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('company_email_bcc', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('company_phone', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('company_activity_field', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('owner_firstname', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('owner_lastname', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='customers_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_customers_owner_lastname', 'customers', ['owner_lastname'], unique=False)
    op.create_index('ix_customers_owner_firstname', 'customers', ['owner_firstname'], unique=False)
    op.create_index('ix_customers_company_activity_field', 'customers', ['company_activity_field'], unique=False)
    op.drop_table('commercial_stage_steps')
    op.drop_table('opportunities')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_contacts_owner_lastname'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_owner_firstname'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_activity_field'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('commercial_stages')
    op.drop_table('status')
    op.drop_table('notes')
    # ### end Alembic commands ###
