""" First migration for test config 

Revision ID: f1de4478cb02
Revises: 3009dcc5afd1
Create Date: 2020-01-12 12:07:43.291945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1de4478cb02'
down_revision = '3009dcc5afd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('company_address', sa.String(length=120), nullable=True),
    sa.Column('company_postal_code', sa.String(length=30), nullable=True),
    sa.Column('company_city', sa.String(length=60), nullable=True),
    sa.Column('company_email', sa.String(length=120), nullable=True),
    sa.Column('company_email_bcc', sa.String(length=120), nullable=True),
    sa.Column('company_phone', sa.String(length=60), nullable=True),
    sa.Column('company_activity_field', sa.String(length=60), nullable=False),
    sa.Column('owner_firstname', sa.String(length=60), nullable=True),
    sa.Column('owner_lastname', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_activity_field'), 'leads', ['company_activity_field'], unique=False)
    op.create_index(op.f('ix_leads_owner_firstname'), 'leads', ['owner_firstname'], unique=False)
    op.create_index(op.f('ix_leads_owner_lastname'), 'leads', ['owner_lastname'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=30), nullable=True),
    sa.Column('monthly_price', sa.Integer(), nullable=True),
    sa.Column('yearly_price', sa.Integer(), nullable=True),
    sa.Column('limit_daily_query', sa.Integer(), nullable=True),
    sa.Column('crm_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_plan_name'), 'plans', ['plan_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('company_address', sa.String(length=120), nullable=True),
    sa.Column('company_postal_code', sa.String(length=30), nullable=True),
    sa.Column('company_city', sa.String(length=60), nullable=True),
    sa.Column('company_email', sa.String(length=120), nullable=True),
    sa.Column('company_email_bcc', sa.String(length=120), nullable=True),
    sa.Column('company_phone', sa.String(length=60), nullable=True),
    sa.Column('company_activity_field', sa.String(length=60), nullable=False),
    sa.Column('owner_firstname', sa.String(length=60), nullable=True),
    sa.Column('owner_lastname', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company_activity_field'), 'customers', ['company_activity_field'], unique=False)
    op.create_index(op.f('ix_customers_owner_firstname'), 'customers', ['owner_firstname'], unique=False)
    op.create_index(op.f('ix_customers_owner_lastname'), 'customers', ['owner_lastname'], unique=False)
    op.create_table('lead_requests',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('lead_id', 'user_id')
    )
    op.create_table('subscriptions',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('yearly', sa.Boolean(), nullable=True),
    sa.Column('subscription_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('lead_requests')
    op.drop_index(op.f('ix_customers_owner_lastname'), table_name='customers')
    op.drop_index(op.f('ix_customers_owner_firstname'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_activity_field'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plans_plan_name'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_leads_owner_lastname'), table_name='leads')
    op.drop_index(op.f('ix_leads_owner_firstname'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_activity_field'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
